
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.110:8501

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog
            
[31m‚îÄ‚îÄ[0m[31m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0m[31m [0m[1;31mTraceback [0m[1;2;31m(most recent call last)[0m[31m [0m[31m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0m[31m‚îÄ‚îÄ[0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/runtime/sc[0m [31m [0m
[31m [0m [2;33mriptrunner/[0m[1;33mexec_code.py[0m:[94m128[0m in [92mexec_func_with_error_handling[0m                         [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/runtime/sc[0m [31m [0m
[31m [0m [2;33mriptrunner/[0m[1;33mscript_runner.py[0m:[94m669[0m in [92mcode_to_exec[0m                                      [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/[0m[1;33mapp.py[0m:[94m2[0m in [92m<module>[0m                                    [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m  1 [0m[94mimport[0m[90m [0m[4;96mstreamlit[0m[90m [0m[94mas[0m[90m [0m[4;96mst[0m                                                         [31m [0m
[31m [0m [31m‚ù± [0m  2 [1;4;94mimport[0m[1;4;90m [0m[1;4;96mgoogle[0m[1;4;96m.[0m[1;4;96mgenerativeai[0m[1;4;90m [0m[1;4;94mas[0m[1;4;90m [0m[1;4;96mgenai[0m                                            [31m [0m
[31m [0m   [2m  3 [0m[94mimport[0m[90m [0m[4;96mos[0m                                                                      [31m [0m
[31m [0m   [2m  4 [0m[94mimport[0m[90m [0m[4;96mrandom[0m                                                                  [31m [0m
[31m [0m   [2m  5 [0m[94mimport[0m[90m [0m[4;96mjson[0m                                                                    [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/google/generativeai/[0m [31m [0m
[31m [0m [1;33m__init__.py[0m:[94m45[0m in [92m<module>[0m                                                           [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m42 [0m                                                                                [31m [0m
[31m [0m   [2m43 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mgenerativeai[0m[90m [0m[94mimport[0m version                                         [31m [0m
[31m [0m   [2m44 [0m                                                                                [31m [0m
[31m [0m [31m‚ù± [0m45 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96mgoogle[0m[1;4;96m.[0m[1;4;96mgenerativeai[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m caching[0m                                         [31m [0m
[31m [0m   [2m46 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mgenerativeai[0m[90m [0m[94mimport[0m protos                                          [31m [0m
[31m [0m   [2m47 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mgenerativeai[0m[90m [0m[94mimport[0m types                                           [31m [0m
[31m [0m   [2m48 [0m                                                                                [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/google/generativeai/[0m [31m [0m
[31m [0m [1;33mcaching.py[0m:[94m21[0m in [92m<module>[0m                                                            [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m 18 [0m[94mimport[0m[90m [0m[4;96mtextwrap[0m                                                                [31m [0m
[31m [0m   [2m 19 [0m[94mfrom[0m[90m [0m[4;96mtyping[0m[90m [0m[94mimport[0m Iterable, Optional                                          [31m [0m
[31m [0m   [2m 20 [0m                                                                               [31m [0m
[31m [0m [31m‚ù± [0m 21 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96mgoogle[0m[1;4;96m.[0m[1;4;96mgenerativeai[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m protos[0m                                         [31m [0m
[31m [0m   [2m 22 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mgenerativeai[0m[4;96m.[0m[4;96mtypes[0m[90m [0m[94mimport[0m caching_types                            [31m [0m
[31m [0m   [2m 23 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mgenerativeai[0m[4;96m.[0m[4;96mtypes[0m[90m [0m[94mimport[0m content_types                            [31m [0m
[31m [0m   [2m 24 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mgenerativeai[0m[4;96m.[0m[4;96mclient[0m[90m [0m[94mimport[0m get_default_cache_client                [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/google/generativeai/[0m [31m [0m
[31m [0m [1;33mprotos.py[0m:[94m74[0m in [92m<module>[0m                                                             [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m71 [0m[33m>>> help(proto.Part.to_dict)[0m                                                    [31m [0m
[31m [0m   [2m72 [0m[33m"""[0m                                                                             [31m [0m
[31m [0m   [2m73 [0m                                                                                [31m [0m
[31m [0m [31m‚ù± [0m74 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96mgoogle[0m[1;4;96m.[0m[1;4;96mai[0m[1;4;96m.[0m[1;4;96mgenerativelanguage_v1beta[0m[1;4;96m.[0m[1;4;96mtypes[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m *[0m                         [31m [0m
[31m [0m   [2m75 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mai[0m[4;96m.[0m[4;96mgenerativelanguage_v1beta[0m[4;96m.[0m[4;96mtypes[0m[90m [0m[94mimport[0m __all__                   [31m [0m
[31m [0m   [2m76 [0m                                                                                [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/google/ai/generative[0m [31m [0m
[31m [0m [2;33mlanguage_v1beta/[0m[1;33m__init__.py[0m:[94m21[0m in [92m<module>[0m                                           [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m 18 [0m__version__ = package_version.__version__                                      [31m [0m
[31m [0m   [2m 19 [0m                                                                               [31m [0m
[31m [0m   [2m 20 [0m                                                                               [31m [0m
[31m [0m [31m‚ù± [0m 21 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96m.[0m[1;4;96mservices[0m[1;4;96m.[0m[1;4;96mcache_service[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m CacheServiceAsyncClient, CacheServiceClien[0m [31m [0m
[31m [0m   [2m 22 [0m[94mfrom[0m[90m [0m[4;96m.[0m[4;96mservices[0m[4;96m.[0m[4;96mdiscuss_service[0m[90m [0m[94mimport[0m DiscussServiceAsyncClient, DiscussServic [31m [0m
[31m [0m   [2m 23 [0m[94mfrom[0m[90m [0m[4;96m.[0m[4;96mservices[0m[4;96m.[0m[4;96mfile_service[0m[90m [0m[94mimport[0m FileServiceAsyncClient, FileServiceClient   [31m [0m
[31m [0m   [2m 24 [0m[94mfrom[0m[90m [0m[4;96m.[0m[4;96mservices[0m[4;96m.[0m[4;96mgenerative_service[0m[90m [0m[94mimport[0m (                                     [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/google/ai/generative[0m [31m [0m
[31m [0m [2;33mlanguage_v1beta/services/cache_service/[0m[1;33m__init__.py[0m:[94m16[0m in [92m<module>[0m                    [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m13 [0m[2m# See the License for the specific language governing permissions and[0m           [31m [0m
[31m [0m   [2m14 [0m[2m# limitations under the License.[0m                                                [31m [0m
[31m [0m   [2m15 [0m[2m#[0m                                                                               [31m [0m
[31m [0m [31m‚ù± [0m16 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96m.[0m[1;4;96masync_client[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m CacheServiceAsyncClient[0m                               [31m [0m
[31m [0m   [2m17 [0m[94mfrom[0m[90m [0m[4;96m.[0m[4;96mclient[0m[90m [0m[94mimport[0m CacheServiceClient                                          [31m [0m
[31m [0m   [2m18 [0m                                                                                [31m [0m
[31m [0m   [2m19 [0m__all__ = (                                                                     [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/google/ai/generative[0m [31m [0m
[31m [0m [2;33mlanguage_v1beta/services/cache_service/[0m[1;33masync_client.py[0m:[94m33[0m in [92m<module>[0m                [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m 30 [0m)                                                                              [31m [0m
[31m [0m   [2m 31 [0m                                                                               [31m [0m
[31m [0m   [2m 32 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[90m [0m[94mimport[0m exceptions [94mas[0m core_exceptions                      [31m [0m
[31m [0m [31m‚ù± [0m 33 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96mgoogle[0m[1;4;96m.[0m[1;4;96mapi_core[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m gapic_v1[0m                                           [31m [0m
[31m [0m   [2m 34 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[90m [0m[94mimport[0m retry_async [94mas[0m retries                             [31m [0m
[31m [0m   [2m 35 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[4;96m.[0m[4;96mclient_options[0m[90m [0m[94mimport[0m ClientOptions                       [31m [0m
[31m [0m   [2m 36 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mauth[0m[90m [0m[94mimport[0m credentials [94mas[0m ga_credentials  [2m# type: ignore[0m          [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/google/api_core/gapi[0m [31m [0m
[31m [0m [2;33mc_v1/[0m[1;33m__init__.py[0m:[94m16[0m in [92m<module>[0m                                                      [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m13 [0m[2m# limitations under the License.[0m                                                [31m [0m
[31m [0m   [2m14 [0m                                                                                [31m [0m
[31m [0m   [2m15 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[4;96m.[0m[4;96mgapic_v1[0m[90m [0m[94mimport[0m client_info                                [31m [0m
[31m [0m [31m‚ù± [0m16 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96mgoogle[0m[1;4;96m.[0m[1;4;96mapi_core[0m[1;4;96m.[0m[1;4;96mgapic_v1[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m config[0m                                     [31m [0m
[31m [0m   [2m17 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[4;96m.[0m[4;96mgapic_v1[0m[90m [0m[94mimport[0m config_async                               [31m [0m
[31m [0m   [2m18 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[4;96m.[0m[4;96mgapic_v1[0m[90m [0m[94mimport[0m method                                     [31m [0m
[31m [0m   [2m19 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[4;96m.[0m[4;96mgapic_v1[0m[90m [0m[94mimport[0m method_async                               [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/google/api_core/gapi[0m [31m [0m
[31m [0m [2;33mc_v1/[0m[1;33mconfig.py[0m:[94m23[0m in [92m<module>[0m                                                        [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m 20 [0m                                                                               [31m [0m
[31m [0m   [2m 21 [0m[94mimport[0m[90m [0m[4;96mcollections[0m                                                             [31m [0m
[31m [0m   [2m 22 [0m                                                                               [31m [0m
[31m [0m [31m‚ù± [0m 23 [1;4;94mimport[0m[1;4;90m [0m[1;4;96mgrpc[0m                                                                    [31m [0m
[31m [0m   [2m 24 [0m                                                                               [31m [0m
[31m [0m   [2m 25 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[90m [0m[94mimport[0m exceptions                                         [31m [0m
[31m [0m   [2m 26 [0m[94mfrom[0m[90m [0m[4;96mgoogle[0m[4;96m.[0m[4;96mapi_core[0m[90m [0m[94mimport[0m retry                                              [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/grpc/[0m[1;33m__init__.py[0m:[94m22[0m  [31m [0m
[31m [0m in [92m<module>[0m                                                                          [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m  19 [0m[94mimport[0m[90m [0m[4;96mlogging[0m                                                                [31m [0m
[31m [0m   [2m  20 [0m[94mimport[0m[90m [0m[4;96msys[0m                                                                    [31m [0m
[31m [0m   [2m  21 [0m                                                                              [31m [0m
[31m [0m [31m‚ù± [0m  22 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96mgrpc[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m _compression[0m                                                 [31m [0m
[31m [0m   [2m  23 [0m[94mfrom[0m[90m [0m[4;96mgrpc[0m[4;96m.[0m[4;96m_cython[0m[90m [0m[94mimport[0m cygrpc [94mas[0m _cygrpc                                    [31m [0m
[31m [0m   [2m  24 [0m[94mfrom[0m[90m [0m[4;96mgrpc[0m[4;96m.[0m[4;96m_runtime_protos[0m[90m [0m[94mimport[0m protos                                       [31m [0m
[31m [0m   [2m  25 [0m[94mfrom[0m[90m [0m[4;96mgrpc[0m[4;96m.[0m[4;96m_runtime_protos[0m[90m [0m[94mimport[0m protos_and_services                          [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m [2;33m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/grpc/[0m[1;33m_compression.py[0m [31m [0m
[31m [0m :[94m20[0m in [92m<module>[0m                                                                      [31m [0m
[31m [0m                                                                                      [31m [0m
[31m [0m   [2m17 [0m[94mfrom[0m[90m [0m[4;96mtyping[0m[90m [0m[94mimport[0m Optional                                                     [31m [0m
[31m [0m   [2m18 [0m                                                                                [31m [0m
[31m [0m   [2m19 [0m[94mimport[0m[90m [0m[4;96mgrpc[0m                                                                     [31m [0m
[31m [0m [31m‚ù± [0m20 [1;4;94mfrom[0m[1;4;90m [0m[1;4;96mgrpc[0m[1;4;96m.[0m[1;4;96m_cython[0m[1;4;90m [0m[1;4;94mimport[0m[1;4m cygrpc[0m                                                 [31m [0m
[31m [0m   [2m21 [0m[94mfrom[0m[90m [0m[4;96mgrpc[0m[4;96m.[0m[4;96m_typing[0m[90m [0m[94mimport[0m MetadataType                                           [31m [0m
[31m [0m   [2m22 [0m                                                                                [31m [0m
[31m [0m   [2m23 [0mNoCompression = cygrpc.CompressionAlgorithm.none                                [31m [0m
[31m‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ[0m
[1;91mImportError: [0m
[1;35mdlopen[0m[1m([0m[35m/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/grpc/_cython/[0m[95mcygr[0m
[95mpc.cpython-313-darwin.so[0m, [1;36m0x0002[0m[1m)[0m: symbol not found in flat namespace 
[32m'_PyDict_SetDefaultRef'[0m
2025-06-22 13:35:50.755 Port 8501 is already in use
2025-06-22 13:36:44.578 Uncaught exception in write_error
Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/bootstrap.py", line 348, in run
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 78, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1848, in _execute
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2761, in get
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 93, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1348, in send_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 100, in write_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 994, in render
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1140, in render_string
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 446, in load
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 476, in _create_template
FileNotFoundError: [Errno 2] No such file or directory: '/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/static/index.html'
2025-06-22 13:37:06.659 Uncaught exception in write_error
Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/bootstrap.py", line 348, in run
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 78, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1848, in _execute
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2761, in get
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 93, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1348, in send_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 100, in write_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 994, in render
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1140, in render_string
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 446, in load
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 476, in _create_template
FileNotFoundError: [Errno 2] No such file or directory: '/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/static/index.html'
2025-06-22 13:37:25.993 Uncaught exception in write_error
Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/bootstrap.py", line 348, in run
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 78, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1848, in _execute
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2761, in get
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 93, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1348, in send_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 100, in write_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 994, in render
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1140, in render_string
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 446, in load
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 476, in _create_template
FileNotFoundError: [Errno 2] No such file or directory: '/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/static/index.html'
2025-06-22 13:37:35.473 Uncaught exception in write_error
Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/bootstrap.py", line 348, in run
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 78, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1848, in _execute
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2761, in get
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 93, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1348, in send_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 100, in write_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 994, in render
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1140, in render_string
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 446, in load
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 476, in _create_template
FileNotFoundError: [Errno 2] No such file or directory: '/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/static/index.html'
2025-06-22 13:37:35.970 Uncaught exception in write_error
Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/bootstrap.py", line 348, in run
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 78, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1848, in _execute
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2761, in get
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 93, in validate_absolute_path
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 2976, in validate_absolute_path
tornado.web.HTTPError: HTTP 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1348, in send_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/web/server/routes.py", line 100, in write_error
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 994, in render
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/web.py", line 1140, in render_string
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 446, in load
  File "/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/tornado/template.py", line 476, in _create_template
FileNotFoundError: [Errno 2] No such file or directory: '/Users/natsus/Desktop/bridge/.venv/lib/python3.13/site-packages/streamlit/static/index.html'
  Stopping...
